
services:
  image-loader:
    container_name: image-loader
    build: src/parser
    volumes:
      - ./config:/app/config
      - ./resources:/app/resources
    ports:
      - "8001:8000"
  complementary-colors:
    container_name: complementary-colors
    build: src/complementary_colors
    volumes:
      - ./config:/app/config
      - ./resources:/app/resources
    ports:
      - "8011:8000"
