services:
  query:
    container_name: query
    build: src/query
    volumes:
      - ./config:/app/config
      - ./resources:/app/resources
    ports:
      - "8080:8080"
  loader:
    container_name: loader
    build: src/loader
    volumes:
      - ./config:/app/config
      - ./resources:/app/resources
    ports:
      - "8001:8001"
    depends_on:
      - query
  complementary-colors:
    container_name: complementary-colors
    build: src/complementary_colors
    volumes:
      - ./config:/app/config
      - ./resources:/app/resources
    ports:
      - "8011:8011"
  crawler:
    container_name: crawler
    build: src/crawler
    volumes:
      - ./config:/app/config
      - ./resources:/app/resources
    ports:
      - "8053:8053"
    depends_on:
      - query
  handler:
    container_name: handler
    build: src/handler
    volumes:
      - ./config:/app/config
      - ./resources:/app/resources
    ports:
      - "8000:8000"
